version: '3.9'

services:
  db:
    image: postgres:alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: randomuser
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: randomdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local